ci(workflow): rollback fusionauth installation with brew - https://github.com/FusionAuth/homebrew-fusionauth/issues/9

diff --git a/.github/workflows/e2e-test-fusionauth-latest-ios-matrix.yml b/.github/workflows/e2e-test-fusionauth-latest-ios-matrix.yml
--- a/.github/workflows/e2e-test-fusionauth-latest-ios-matrix.yml
+++ b/.github/workflows/e2e-test-fusionauth-latest-ios-matrix.yml
@@ -121,15 +121,16 @@ jobs:
       #    FUSIONAUTH_VERSION: ${{ env.fusionauth-docker-image-version }}
       #    FUSIONAUTH_APP_KICKSTART_DIRECTORY_PATH: Samples/Quickstart/fusionauth/${{ env.fusionauth-docker-image-version }}/kickstart
 
+      # FusionAuth deployment fails https://github.com/FusionAuth/homebrew-fusionauth/issues/9
       # Install FusionAuth with brew.
-      - name: Install FusionAuth
-        env:
-          FUSIONAUTH_APP_KICKSTART_FILE: "Samples/Quickstart/fusionauth/${{ env.fusionauth-docker-image-version }}/kickstart/kickstart.json"
-        run: |
-          brew tap fusionauth/homebrew-fusionauth
-          brew install fusionauth-app fusionauth-search
-          brew services start fusionauth-search
-          brew services start fusionauth-app
+      #- name: Install FusionAuth
+      #  env:
+      #    FUSIONAUTH_APP_KICKSTART_FILE: "Samples/Quickstart/fusionauth/${{ env.fusionauth-docker-image-version }}/kickstart/kickstart.json"
+      #  run: |
+      #    brew tap fusionauth/homebrew-fusionauth
+      #    brew install fusionauth-app fusionauth-search
+      #    brew services start fusionauth-search
+      #    brew services start fusionauth-app
 
       # Checkout the repository.
       - name: Checkout repository
@@ -137,4 +138,4 @@ jobs:
 
       # Perform the tests from the fusionauth-quickstart-swift-ios-native Sample.
       - name: Perform end to end tests
-        run: set -o pipefail && xcodebuild test -workspace FusionAuthSDK.xcworkspace/ -scheme fusionauth-quickstart-swift-ios-native -destination "${{matrix.destination}}" -skipPackagePluginValidation
+        run: set -o pipefail && xcodebuild -workspace FusionAuthSDK.xcworkspace/ -scheme fusionauth-quickstart-swift-ios-native -destination "${{matrix.destination}}" -skipPackagePluginValidation
