feat(e2e-test): add fusionauth instance

diff --git a/.github/workflows/e2e-test-fusionauth-latest-ios-matrix.yml b/.github/workflows/e2e-test-fusionauth-latest-ios-matrix.yml
--- a/.github/workflows/e2e-test-fusionauth-latest-ios-matrix.yml
+++ b/.github/workflows/e2e-test-fusionauth-latest-ios-matrix.yml
@@ -40,6 +40,7 @@ jobs:
         simulator-version: [ "18.1" ]
         swift: ["5.10.1"]
         os: [ "macos-14" ]
+        postgresql-version: [ "16" ]
         include:
           - destination: "platform=iOS Simulator,OS=17.5,name=iPhone 15"
             xcode: "15.4"
@@ -47,18 +48,21 @@ jobs:
             simulator-version: "17.5"
             swift: "5.10.1"
             os: "macos-14"
+            postgresql-version: "16"
           - destination: "platform=iOS Simulator,OS=16.4,name=iPhone 14"
             xcode: "14.3.1"
             simulator-platform: "iOS"
             simulator-version: "16.4"
             swift: "5.8.1"
             os: "macos-13"
+            postgresql-version: "16"
           - destination: "platform=iOS Simulator,OS=15.5,name=iPhone 13"
             xcode: "14.3.1"
             simulator-platform: "iOS"
             simulator-version: "15.5"
             swift: "5.8.1"
             os: "macos-13"
+            postgresql-version: "16"
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
@@ -132,10 +136,101 @@ jobs:
       #    brew services start fusionauth-search
       #    brew services start fusionauth-app
 
+      # Install FusionAuth with brew.
+      - name: Install PostgreSQL
+        run: brew install postgresql@${{ matrix.postgresql-version }} -v
+
+      # Start PostgreSQL with brew.
+      - name: Start PostgreSQL
+        run: brew services start postgresql@${{ matrix.postgresql-version }} -v
+
+      # Add PostgreSQL to the PATH.
+      - name: Add PostgreSQL to the PATH
+        run: echo "$(brew --prefix postgresql@${{matrix.postgresql-version }})/bin" >> $GITHUB_PATH
+
+      # Add PostgreSQL fusionauth user with default password.
+      - name: Add PostgreSQL fusionauth user
+        run: psql --command="CREATE USER fusionauth PASSWORD 'fusionauth'" --command="\du" postgres
+
+      # Add PostgreSQL fusionauth database.
+      - name: Add PostgreSQL fusionauth database
+        run: createdb --owner=fusionauth fusionauth
+
+      # Tap FusionAuth Homebrew formulae.
+      - name: Tap FusionAuth Homebrew formulae
+        run: brew tap sonderformat-llc/fusionauth
+
+      # Install FusionAuth Search with brew.
+      - name: Install FusionAuth Search
+        run: brew install fusionauth-search -v
+
+      # Install FusionAuth App with brew.
+      - name: Install FusionAuth App
+        run: brew install fusionauth-app -v
+
+      # Configure FusionAuth App with silent mode.
+      - name: Configure FusionAuth App
+        run: |
+          echo "" >> $(brew --prefix)/etc/fusionauth/fusionauth.properties
+          echo "fusionauth-app.kickstart.file=$(echo $GITHUB_WORKSPACE)/Samples/Quickstart/fusionauth/${{ env.fusionauth-docker-image-version }}/kickstart/kickstart.json" >> $(brew --prefix)/etc/fusionauth/fusionauth.properties
+          echo "fusionauth-app.silent-mode=true" >> $(brew --prefix)/etc/fusionauth/fusionauth.properties
+          cat $(brew --prefix)/etc/fusionauth/fusionauth.properties
+
+      # Start FusionAuth Search.
+      - name: Start FusionAuth Search
+        run: brew services start fusionauth-search -v
+
+      # Start FusionAuth App.
+      - name: Start FusionAuth App
+        run: brew services start fusionauth-app -v
+
+      # Check Brew services status.
+      - name: Check Brew services status
+        run: brew services list
+
+      # Check FusionAuth status 10 times with increasing wait times
+      # Continue if FusionAuth status is OK or fail at the end.
+      - name: Check FusionAuth status
+        run: |
+          for i in {1..10}; do
+            if curl -s http://localhost:9011/api/status | grep -qi "ok"; then
+              echo "FusionAuth is up and running."
+              exit 0
+            else
+              echo "FusionAuth is not up and running. Waiting for $(expr 10 \* $i) seconds."
+              sleep $(expr 10 \* $i)
+            fi
+          done
+          exit 1
+
+      # Check KickstartRunner execution 10 times with increasing wait times
+      # Continue if KickstartRunner execution is OK or fail at the end.
+      # TODO - use webhook instead https://fusionauth.io/docs/extend/events-and-webhooks/events/kickstart-success
+      - name: Check KickstartRunner execution
+        run: |
+          for i in {1..10}; do
+            if cat $(brew --prefix)/var/log/fusionauth/fusionauth-app.log | grep "KickstartRunner" | grep -q "Summary"; then
+              echo "KickstartRunner execution is OK."
+              exit 0
+            else
+              echo "KickstartRunner execution is not OK. Waiting for $(expr 10 \* $i) seconds."
+              sleep $(expr 10 \* $i)
+            fi
+          done
+          exit 1
+
+      # Read FusionAuth App logs.
+      - name: Read FusionAuth App logs
+        run: cat $(brew --prefix)/var/log/fusionauth/fusionauth-app.log
+
+      # Connect to FusionAuth App.
+      - name: Connect to FusionAuth App
+        run: curl http://localhost:9011/api/status
+
       # Checkout the repository.
       - name: Checkout repository
         uses: actions/checkout@v4.2.2
 
       # Perform the tests from the fusionauth-quickstart-swift-ios-native Sample.
       - name: Perform end to end tests
-        run: set -o pipefail && xcodebuild -workspace FusionAuthSDK.xcworkspace/ -scheme fusionauth-quickstart-swift-ios-native -destination "${{matrix.destination}}" -skipPackagePluginValidation
+        run: set -o pipefail && xcodebuild test -workspace FusionAuthSDK.xcworkspace/ -scheme fusionauth-quickstart-swift-ios-native -destination "${{matrix.destination}}" -skipPackagePluginValidation
